development:
  adapter: postgresql
  encoding: unicode
  database: repo_reader_development
  pool: 5
  username: jasonramirez
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: repo_reader_test
  pool: 5
  username: jasonramirez
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: repo_reader_production
  pool: 5
  username: jasonramirez
  password: password
