development: &default
  adapter: postgresql
  database: repo_reader_development
  encoding: unicode
  host: localhost
  pool: 5
  # username: jasonramirez
  # password: password

test:
  <<: *default
  database: repo_reader_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  # url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
